language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 Home이다
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

before_deploy:
  - zip -r spring-service * #현재위치 모든파일을 spring-service로 압축함
  - mkdir -p deploy
  - mv spring-service.zip deploy/spring-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # 설정한 값
    secret_access_key: $AWS_SECRET_KEY # 설정한 값
    bucket: spring-service-build #s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip파일접근 private으로 변경
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - suriessay@gmail.com